Name:           ros-melodic-novatel-gps-driver
Version:        3.5.0
Release:        0%{?dist}
Summary:        ROS novatel_gps_driver package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       libpcap-devel
Requires:       ros-melodic-diagnostic-msgs
Requires:       ros-melodic-diagnostic-updater
Requires:       ros-melodic-gps-common
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-nodelet
Requires:       ros-melodic-novatel-gps-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-swri-math-util
Requires:       ros-melodic-swri-nodelet
Requires:       ros-melodic-swri-roscpp
Requires:       ros-melodic-swri-serial-util
Requires:       ros-melodic-swri-string-util
Requires:       ros-melodic-tf
BuildRequires:  boost-devel
BuildRequires:  libpcap-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-diagnostic-updater
BuildRequires:  ros-melodic-gps-common
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-nodelet
BuildRequires:  ros-melodic-novatel-gps-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-swri-math-util
BuildRequires:  ros-melodic-swri-nodelet
BuildRequires:  ros-melodic-swri-roscpp
BuildRequires:  ros-melodic-swri-serial-util
BuildRequires:  ros-melodic-swri-string-util
BuildRequires:  ros-melodic-tf

%description
Driver for NovAtel receivers

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Jul 17 2018 P. J. Reed <preed@swri.org> - 3.5.0-0
- Autogenerated by Bloom

* Wed May 30 2018 P. J. Reed <preed@swri.org> - 3.4.0-0
- Autogenerated by Bloom

